import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full">
        <div className="flex min-h-screen">
          {/* Sidebar */}
          <aside className="w-sidebar-width bg-surface border-r border-outline-variant">
            {/* TODO: Sidebar component */}
          </aside>
          <div className="flex-1 flex flex-col">
            {/* Header */}
            <header className="h-16 bg-surface border-b border-outline-variant flex items-center px-layout-gutter">
              {/* TODO: Header component */}
            </header>
            {/* Main content */}
            <main className="flex-1 bg-background p-layout-gutter">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
